### PR TITLE
cross off auto cancel - not yet in docs, but functional

### PR DESCRIPTION
**Pull request by ndintenfass**

### CODE REVIEW

**Comment by samandmoore** [comment]
@ndintenfass does this mean that there is not auto-canceling of redundant workflow builds?

**Comment by gordonsyme** [comment]
@samandmoore the opposite! It's crossing auto-cancel off the TODO list :)

**Comment by samandmoore** [comment]
Excellent. Does this feature depend on enabling anything in settings?

**Comment by ndintenfass** [comment]
@samandmoore you do need to turn on build processing under the Advanced Settings section of your project settings (and, of course, have the auto cancel option on as well, which is also on that settings page).

**Comment by samandmoore** [comment]
Perfect! Thanks for building this out. I’m really excited for it.

**Pull request merged**
